### PR TITLE
FastifyInstance as argument for healthCheck; Closes #103

### PR DESCRIPTION
**Pull request by KODerFunk**
I use `under-pressure` through https://github.com/fastify/fastify-nextjs#under-pressure and isolate underPressure options in `underPressureOptions.ts`. And what's funny is I just need  `fastifyInstance.memoryUsage()` method for extends positive response. (for negative, I use `pressureHandler` and `reply.server.memoryUsage()`).

- Closes #103
- Helpful for #80-like needs

#### Checklist

- [x] run `npm run test`
- [x] tests are included
- [x] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by climba03003 — COMMENTED** [review]
I think `fastify` and `instance` should be always identical as this plugin is wrapped by `fastify-plugin`. The below two snippet should get the same result.
```
fastify.register(underPressure, {
  healthCheck: async function(instance) {
     return instance.memoryUsage()
  }
})

fastify.register(underPressure, {
  healthCheck: async function() {
     return fastify.memoryUsage()
  }
})
```

I want to know that what is this PR trying to solve? Is it only used to provide a shortcut reference to the `instance`? Can it be an example only?

**Comment by KODerFunk** [comment]
@climba03003 of course. 
Again, I am work on large and high-load app, use Next.js and Fastify for custom server. I use official plugin `fastify-nextjs` with builtin [under-pressure](https://github.com/fastify/fastify-nextjs#under-pressure), and code of custom server like this:
```ts
// server/custom/index.ts

import fastify from 'fastify'
import fastifyNextjs from 'fastify-nextjs'

import underPressureOptions from './underPressureOptions'
import drawRoutes from './drawRoutes'

const fastifyInstance = fastify({
  genReqId: ...,
  logger: ...,
  pluginTimeout: ...,
  ...,
})

void fastifyInstance
  .register(fastifyNextjs, {
    noServeAssets: true, // https://github.com/fastify/fastify-nextjs#assets-serving
    underPressure: process.env.NODE_ENV !== 'production' && underPressureOptions,
  })
  .after((error) => {
    if (error) {
      throw error
    }

    drawRoutes(fastifyInstance)
  })

...
```

and have isolated `underPressureOptions.ts` like this:

```ts
const SERVICE_UNAVAILABLE = 503
const second = 1000
const retryAfter = 10

const underPressureOptions: underPressure.UnderPressureOptions = {
  healthCheck: (fastifyInstance) => Promise.resolve({
    // >>>>>>>> Positive response with current metrics.  <<<<<<<<
    // >>>>>>>> Can get access thanks to this PR. <<<<<<<<
    metrics: fastifyInstance.memoryUsage(),
  }),
  pressureHandler: (_req, reply, type, value) => {
    void reply
      .status(SERVICE_UNAVAILABLE)
      .header('Retry-After', retryAfter)
      .send({
        status: 'down',
        reason: {
          type,
          value,
        },
        // >>>>>>>> Negative response with current metrics.  <<<<<<<<
        // >>>>>>>> Already Access to `memoryUsage` over Fastify instance from `reply` arg. <<<<<<<<
        metrics: reply.server.memoryUsage(),
      })
  },
}

export default underPressureOptions
```

Maybe i can make `createUnderPressureOptions.ts` with dependency injection like:
```ts
export default createUnderPressureOptions(fastifyInstance: FastifyIndex): underPressure.UnderPressureOptions {
  return {
    ...
  }
}
```
**And this variant also does not work with the current version**, as decoration `memoryUsage` method occurs after the first call `healthCheck` during initialization plugin.

But it seems to me that what I did in this PR:
1) Does not hurt anyone.
3) Easy access to `memoryUsage()` decorated in `fastifyInstance`.
2) Compliance [encapsulation](https://www.fastify.io/docs/latest/Encapsulation/).

**Comment by climba03003** [comment]
Will it be better to pass the value of `memeryUsage` throw argument? because, the function is only used to get the computed value. You can directly handle the data, instead of calling function each time before using it.

**Comment by KODerFunk** [comment]
@climba03003 no. 
1) Is it I need to call `memoryUsage()`, someone else or I will later need to call another decorated method. 
2) Passing a reference to an argument is almost free, as opposed to getting method results, which most developers won't need.

**Comment by KODerFunk** [comment]
@mcollina Hi! This PR can close two others:

- https://github.com/fastify/under-pressure/pull/80
- https://github.com/fastify/under-pressure/pull/103

**Review by mcollina — APPROVED** [review]
lgtm

**Review by climba03003 — APPROVED** [review]
I have no more question. LGTM.
@KODerFunk  You can update your description and add `Closes #XX` if you think this PR will close the others.

**Comment by KODerFunk** [comment]
@mcollina, @climba03003 TY!

100% closes #103 

And maybe it can help people with needs like in #80.

**Comment by KODerFunk** [comment]
@mcollina hi! Sorry to bother you, but how soon can we expect a new release with this changes? 
I need to plan the introduction of these changes in our application.

**Pull request merged**
