### PR TITLE
Fix clearing timeout using clearTimeout

### PR DESCRIPTION
**Pull request by karankraina**
#### Checklist

- [ ] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by karankraina** [comment]
@mcollina Could you please have a look at this. I think we should clear the timeouts using ```clearTimeout``` instead of ```setInterval```

**Review by mcollina — APPROVED** [review]
lgtm

**Review by gurgunday — APPROVED** [review]

**Comment by karankraina** [comment]
Thanks @mcollina @gurgunday. Checks have completed, it can be merged now.

**Review by Uzlopak — APPROVED** [review]
LGTM

At some Point we switched from a interval to a timeout and never set the right clear function.

**Pull request merged**
